### ISSUE TITLE
Resize group when the cgDescription is updated.

### ISSUE THREAD

**Issue by jeremt** [dudeteam/dude-graph#109]
![bug](https://gyazo.com/61895b4189cfd928260bfc434911a410.png)

**Comment by JonathanPicques** [comment]
I cannot reproduce the error
![bug](https://i.gyazo.com/d1723738a6c5c7bb7c13e9bc62d09423.gif)

**Comment by jeremt** [comment]
It wasn't working when I reported it. Seems to be fixed, I'm closing.
