### ISSUE TITLE
Some bugs with the number of connections for a point.

### ISSUE THREAD

**Issue by jeremt** [dudeteam/dude-graph#110]

**Comment by jeremt** [comment]
The cgMaxConnections accepts a specific number of connection. However, the usecase are either 1 or an infinite number of connections. So, in my opinion, cgMaxConnections should be replaced by an enumeration (ONE, SEVERAL) or something like that.

**Comment by JonathanPicques** [comment]
Actually cgMaxConnections can be 0, 1 or Infinity

Le dim. 20 sept. 2015 à 15:38, Jeremie Taboada notifications@github.com a
écrit :

**Comment by jeremt** [comment]
Yes I realised that, it was just missing in some blocks, I'm closing.
