### ISSUE TITLE
Handle cgValue and cgConnections in Point

### ISSUE THREAD

**Issue by JonathanPicques** [dudeteam/dude-graph#122]
Discuss what would be the correct solution of adding a cgValue when a connection exists, or the other way round.

**Comment by JonathanPicques** [comment]
Parameter:
@param {Boolean} cgValueActsAsConnection
If True, cgValue acts as a connections, with the same rules (cgMaxConnections)
If False, the point can only have A cgValue OR cgConnections

**Comment by JonathanPicques** [comment]
cgValue will be treated like a "wireless" connection

**Comment by jeremt** [comment]
👍
