### ISSUE TITLE
Change dude-graph theme, the contrast between blocks and the background is way too low

### ISSUE THREAD

**Issue by JonathanPicques** [dudeteam/dude-graph#165]
![image](https://cloud.githubusercontent.com/assets/1839757/12702136/3acdfed4-c81f-11e5-97c1-e0fe999573a9.png)

**Comment by jeremt** [comment]
@JonathanPicques Hmm, indeed, but that's weird because it's already working for me. Maybe bower isnt up to date.

**Comment by jeremt** [comment]
https://i.gyazo.com/507b9d29d09d5585a043b5d6ea228330.png

**Comment by JonathanPicques** [comment]
I reinstalled node packages and bower packages and the contrast is still low,
You should: `rm -rf node_modules bower_components && npm install && bower install` on your end and give it another go.
