### ISSUE TITLE
The styleUrl attribute should not be null

### ISSUE THREAD

**Issue by JonathanPicques** [dudeteam/dude-graph#39]
Chrome and Firefox report a warning: The styleUrl attribute should not be null (cg-style.html:46)

Also this in Chrome only:
![image](https://cloud.githubusercontent.com/assets/1839757/6828193/3ee5a6c2-d304-11e4-8327-34a64c2fd501.png)

**Comment by jeremt** [comment]
Fixed in new dude-config element.
